#! /bin/bash

# AUTHOR:	(c) Jason Horan
# NAME:	PDF Password Remove
# DESCRIPTION:	A nice Nautilus script with a GUI to remove password from PDF files
# REQUIRES:	pdftk, zenity
# LICENSE:	GNU GPL v3 (http://www.gnu.org/licenses/gpl.html)
# ACKNOWLEDGE:	Ricardo Ferreira Compress PDF https://launchpad.net/compress-pdf
#		My colleagues who have assisted with the translations

# Messages
		# English (en-US)
		error_nofiles="No file selected."
		error_pdftk="PDF Remove Password requires the 'pdftk' package, which is not installed. Please install it and try again.  It is available in apt and as a snap."
		error_nopdf="The selected file is not a valid PDF archive."
		error_norun="The command could not run correctly."
		job_done="has been successfully decoded."

case $LANG in

	pl* )
		# Polish (pl-PL) by Ania Lala
		error_nofiles="Nie wybrano pliku."
		error_pdftk="Ochrona hasłem PDF wymaga pakietu „pdftk”, który nie jest zainstalowany. Zainstaluj go i spróbuj ponownie. Jest dostępny w apt i na przystawkę."
		error_nopdf="Wybrany plik nie jest prawidłowym archiwum PDF."
		error_norun="Polecenie nie moglo zostać wykonane poprawnie."
		job_done="został pomyślnie zdekodowany.";;

	es* )
		# Spanish (es-AR) by Maury Guerrero
		error_nofiles="No se detectó ningún archivo."
		error_pdftk="El PDF protegido por contraseña requiere el paquete ‘pdftk’, el cual no está instalado. Instálelo e intente nuevamente. Está disponible en apt y como snap."
		error_nopdf="El archivo seleccionado no es un archivo PDF válido."
		error_norun="El comando no se pudo ejecutar correctamente."
		job_done="ha sido decodificado exitosamente.";;

	cs*)
﻿		# Czech (cz-CZ) by Hariraj Ji
		error_nofiles="Žádný soubor není vybrán."
		error_pdftk="Ochrana PDF heslem vyžaduje balíček „pdftk“, který není nainstalován. Nainstalujte si jej prosím a zkuste to znovu. Je k dispozici v apt a jako ‘snap’."
		error_nopdf="Vybraný soubor není platným PDF archivem."
		error_norun="Příkaz nebylo možno správně spustit."
		job_done="byl úspěšně dekódován.";;

	fr*)
﻿		# French (fr-FR) by Georgios Diakidis
		error_nofiles="Aucun fichier sélectionné."
		error_pdftk="PDF Password Protect nécessite le package «pdftk», qui n'est pas installé. Veuillez l'installer et réessayer. Il est disponible en apt et en un clin d'œil."
		error_nopdf="Le fichier sélectionné n'est pas une archive PDF valide."
		error_norun="La commande n'a pas pu s'exécuter correctement."
		job_done="a été décodé avec succès.";;

	el*)
﻿		# Greek (el-EL) by Georgios Diakidis
		error_nofiles="Δεν έχει επιλεγεί κανένα αρχείο."
		error_pdftk="Το PDF Password Protect απαιτεί το πακέτο «pdftk», το οποίο δεν είναι εγκατεστημένο. Παρακαλούμε, εγκαταστήστε το και δοκιμάστε ξανά. Είναι διαθέσιμο σε πακέτο apt και σε snap."
		error_nopdf="Το επιλεγμένο αρχείο δεν είναι ένα έγκυρο αρχείο PDF."
		error_norun="Δεν ήταν δυνατή η σωστή εκτέλεση της εντολής."
		job_done="έχει αποκωδικοποιηθεί με επιτυχία.";;
		
	it*)
﻿		# Italian (it-IT) by Georgios Diakidis
		error_nofiles="Nessun file selezionato."
		error_pdftk="PDF Password Protect richiede il pacchetto "pdftk", che non è installato. Si prega di installarlo e di riprovare. È disponibile in apt e snap."
		error_nopdf="Il file selezionato non è un archivio PDF valido."
		error_norun="Il comando non può essere eseguito correttamente."
		job_done="è stato decodificato con successo.";;

	zh_CN*)
		# Simplified Chinese  (zh_CN) by Paul Ayadoe
		error_nofiles="没选择文件。"
		error_pdftk="PDF Password Protect需要未安装的“ pdftk”软件包。 请安装它，然后重试。 它可以以apt的形式提供。"
		error_nopdf="所选文件不是有效的PDF存档。"
		error_norun="该命令无法正确运行。"
		job_done="已成功解码。";;

        ar*)
                # Arabic (ar) by Khalid Siddig Abdalla Mohamed
		error_nofiles=".لايوجد ملف محدد"
		error_pdftk="ملف بدف محمي بكلمة سر ويحتاج لحزمة بدف تك, وهي غير متوفرة حاليا. الرجاء تنزيل الحزمة المذكورة أعلاه مرة أخرى. الحزمة متوفرة في نظام ابت  وكذلك نظام سناب."
		error_nopdf="PDF الملف المحدد غير صالح في صيغة"
		error_norun=".لا يمكن تشغيل الأمر بشكل صحيح"
		job_done=".تم فك الشفرة بنجاح";;
		
        ur*)
                # Urdu (ur) by Asim Nayeem
		error_nofiles=".کوئی فائل منتخب نہیں کی گئی"
		error_pdftk="پی ڈی ایف پاس ورڈ پروٹیکٹ کیلئے 'pdftk' پیکیج کی ضرورت ہے ، جو انسٹال نہیں ہے۔ براہ کرم اسے انسٹال کریں اور دوبارہ کوشش کریں۔ یہ آپٹ میں اور ایک تصویر کے طور پر دستیاب ہے۔"
		error_nopdf="اس نے منتخب کیا فائل درست PDF محفوظ شدہ دستاویزات نہیں ہے۔"
		error_norun="کمانڈ صحیح طور پر نہیں چل سکی۔"
		job_done="کامیابی کے ساتھ ضابطہ کشائی کی گئی ہے۔";;

esac

VERSION="1.0"
ZENITY=$(which zenity)

pdf_file=$(basename "$1")

# Check if pdftk is installed
TK="/etc/alternatives/pdftk"
if [ ! -x $TK ]; then
        $ZENITY --error --title="PDF Remove Password "$VERSION"" --text="$error_pdftk"
        exit 0;
fi

# Check if the user has selected any files
if [ -z "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" ]; then
        $ZENITY --error --title="PDF Remove Password "$VERSION"" --text="$error_nofiles"
        exit 0;
fi

# Check if password present already
protected=0
pdftk "$pdf_file" dump_data output /dev/null dont_ask || protected=1
if [ "$protected" = 0 ] ; then
	$ZENITY --error --title="PDF Password Protect "$VERSION"" --text="$error_norun"
	exit 1;
fi

# Choose password
password=$(zenity --entry --title "PDF Remove Password "$VERSION"" --text "Enter User Password" --width 250)
if [[ "$?" != "0" ]] ; then
    exit 0
fi

# Check if the selected file is a PDF
mimetype=$(file -b -i "$1")
if [ -z "`echo $mimetype | grep -i 'pdf' `" ]; then
	$ZENITY --error --title="PDF Remove Password "$VERSION"" --text="$error_nopdf"
        exit 0;
fi

# Create /Done directory if it does not exist
mkdir -p Done

# Set output file name to /Done/<current_filename>
suggested_filename="$pdf_file"
output_filename=Done/"$suggested_filename"

if [ "$?" = 1 ] ; then
        exit 0;
fi

# Remove password from PDF file
pdftk "$suggested_filename" input_pw $password output "$output_filename"
if [ "$?" -ne 0 ] ; then
        $ZENITY --error --title="PDF Remove Password "$VERSION"" --text="$error_norun"
        exit 0;
fi
notify-send "PDF Remove Password" "$pdf_file $job_done"

